import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { toast } from "sonner";
import { Loader2, Upload, X, CheckCircle2 } from "lucide-react";

const supportTicketSchema = z.object({
  subject: z.string().min(5, "Subject must be at least 5 characters").max(200),
  message: z.string().min(10, "Message must be at least 10 characters").max(5000),
});

type SupportTicketFormData = z.infer<typeof supportTicketSchema>;

interface SupportTicketFormProps {
  exhibitorId: string;
}

export const SupportTicketForm = ({ exhibitorId }: SupportTicketFormProps) => {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [files, setFiles] = useState<File[]>([]);
  const [uploadProgress, setUploadProgress] = useState<number[]>([]);
  const [ticketNumber, setTicketNumber] = useState<string | null>(null);

  const {
    register,
    handleSubmit,
    formState: { errors },
    reset,
  } = useForm<SupportTicketFormData>({
    resolver: zodResolver(supportTicketSchema),
  });

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files) {
      const newFiles = Array.from(e.target.files);
      setFiles((prev) => [...prev, ...newFiles]);
      setUploadProgress((prev) => [...prev, ...newFiles.map(() => 0)]);
    }
  };

  const removeFile = (index: number) => {
    setFiles((prev) => prev.filter((_, i) => i !== index));
    setUploadProgress((prev) => prev.filter((_, i) => i !== index));
  };

  const uploadFiles = async (): Promise<string[]> => {
    const uploadedUrls: string[] = [];

    for (let i = 0; i < files.length; i++) {
      const file = files[i];
      const fileExt = file.name.split(".").pop();
      const fileName = `${exhibitorId}/${Date.now()}-${Math.random().toString(36).substring(7)}.${fileExt}`;

      setUploadProgress((prev) => {
        const newProgress = [...prev];
        newProgress[i] = 50;
        return newProgress;
      });

      const { data, error } = await supabase.storage
        .from("support-attachments")
        .upload(fileName, file);

      if (error) {
        console.error("Error uploading file:", error);
        toast.error(`Failed to upload ${file.name}: ${error.message}`);
        throw new Error(`Failed to upload ${file.name}`);
      }

      const { data: { publicUrl } } = supabase.storage
        .from("support-attachments")
        .getPublicUrl(fileName);

      uploadedUrls.push(publicUrl);

      setUploadProgress((prev) => {
        const newProgress = [...prev];
        newProgress[i] = 100;
        return newProgress;
      });
    }

    return uploadedUrls;
  };

  const onSubmit = async (data: SupportTicketFormData) => {
    setIsSubmitting(true);

    try {
      // Upload files first if any
      let attachmentUrls: string[] = [];
      if (files.length > 0) {
        attachmentUrls = await uploadFiles();
      }

      // Create support ticket in database
      const { data: ticket, error: ticketError } = await supabase
        .from("support_tickets")
        .insert({
          exhibitor_id: exhibitorId,
          subject: data.subject,
          message: data.message,
          attachment_urls: attachmentUrls,
          ticket_number: "", // Will be auto-generated by trigger
        })
        .select()
        .maybeSingle();

      if (ticketError) {
        throw ticketError;
      }

      // Send email notification
      const { error: emailError } = await supabase.functions.invoke(
        "send-support-ticket-email",
        {
          body: {
            ticketNumber: ticket.ticket_number,
            exhibitorId,
            subject: data.subject,
            message: data.message,
            attachmentUrls,
          },
        }
      );

      if (emailError) {
        console.error("Error sending email:", emailError);
        toast.error("Ticket created but email notification failed");
      } else {
        toast.success(`Support ticket #${ticket.ticket_number} submitted successfully!`);
      }

      setTicketNumber(ticket.ticket_number);
      reset();
      setFiles([]);
      setUploadProgress([]);
    } catch (error) {
      console.error("Error submitting support ticket:", error);
      
      // Determine specific error type and provide user-friendly message
      let errorTitle = "Unable to Submit Ticket";
      let errorMessage = "";
      let errorAction = "";
      
      if (error instanceof Error) {
        const errorText = error.message.toLowerCase();
        
        if (errorText.includes("network") || errorText.includes("fetch") || errorText.includes("failed to fetch")) {
          errorTitle = "Connection Error";
          errorMessage = "Unable to connect to the server.";
          errorAction = "Please check your internet connection and try again.";
        } else if (errorText.includes("timeout")) {
          errorTitle = "Request Timeout";
          errorMessage = "The server took too long to respond.";
          errorAction = "Please wait a moment and try again.";
        } else if (errorText.includes("upload") || errorText.includes("file")) {
          errorTitle = "File Upload Failed";
          errorMessage = error.message;
          errorAction = "Please try removing the attachments and submitting again, or use smaller files.";
        } else if (errorText.includes("rate limit") || errorText.includes("too many")) {
          errorTitle = "Too Many Requests";
          errorMessage = "You've made too many submissions in a short time.";
          errorAction = "Please wait a few minutes before trying again.";
        } else if (errorText.includes("server") || errorText.includes("500") || errorText.includes("internal")) {
          errorTitle = "Server Error";
          errorMessage = "Something went wrong on our end.";
          errorAction = "Please try again later. If the problem persists, contact support.";
        } else if (errorText.includes("duplicate") || errorText.includes("already exists")) {
          errorTitle = "Duplicate Submission";
          errorMessage = "A similar ticket may have already been submitted.";
          errorAction = "Please check your email for confirmation or try again with a different subject.";
        } else {
          errorMessage = error.message;
          errorAction = "Please try again. If the problem continues, contact us directly.";
        }
      } else {
        errorMessage = "An unexpected error occurred while submitting your ticket.";
        errorAction = "Please try again. If the problem continues, contact us directly.";
      }
      
      toast.error(errorTitle, {
        description: `${errorMessage} ${errorAction}`,
        duration: 8000,
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  if (ticketNumber) {
    return (
      <div className="flex flex-col items-center justify-center py-12 px-4 text-center">
        <div className="mb-6">
          <CheckCircle2 className="w-20 h-20 text-green-500 mx-auto" />
        </div>
        <h2 className="text-2xl font-bold mb-2 text-foreground">Ticket Submitted Successfully!</h2>
        <div className="bg-primary/10 border-2 border-primary rounded-lg p-6 mb-6 max-w-md">
          <p className="text-sm text-muted-foreground mb-2">Your Ticket Number</p>
          <p className="text-3xl font-bold text-primary">#{ticketNumber}</p>
        </div>
        <p className="text-muted-foreground mb-6 max-w-md">
          Your support ticket has been submitted and sent to our client relations team. 
          You will receive a copy of this ticket via email. Please reference this ticket number in any future correspondence.
        </p>
        <Button onClick={() => setTicketNumber(null)}>
          Submit Another Ticket
        </Button>
      </div>
    );
  }

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
      <div className="space-y-2">
        <Label htmlFor="subject">Subject *</Label>
        <Input
          id="subject"
          {...register("subject")}
          placeholder="Brief description of your issue"
          disabled={isSubmitting}
          className="bg-background"
        />
        {errors.subject && (
          <p className="text-sm text-destructive">{errors.subject.message}</p>
        )}
      </div>

      <div className="space-y-2">
        <Label htmlFor="message">Message *</Label>
        <Textarea
          id="message"
          {...register("message")}
          placeholder="Please provide detailed information about your inquiry or issue..."
          rows={8}
          disabled={isSubmitting}
          className="bg-background"
        />
        {errors.message && (
          <p className="text-sm text-destructive">{errors.message.message}</p>
        )}
      </div>

      <div className="space-y-2">
        <Label htmlFor="attachments">Attachments (Optional)</Label>
        <div className="border-2 border-dashed border-border rounded-lg p-6 text-center hover:border-primary/50 transition-colors">
          <input
            type="file"
            id="attachments"
            multiple
            onChange={handleFileChange}
            disabled={isSubmitting}
            className="hidden"
          />
          <label
            htmlFor="attachments"
            className="cursor-pointer flex flex-col items-center justify-center"
          >
            <Upload className="w-10 h-10 text-muted-foreground mb-2" />
            <span className="text-sm text-muted-foreground">
              Click to upload files or drag and drop
            </span>
            <span className="text-xs text-muted-foreground mt-1">
              PDF, DOC, DOCX, JPG, PNG (Max 10MB each)
            </span>
          </label>
        </div>

        {files.length > 0 && (
          <div className="mt-4 space-y-2">
            {files.map((file, index) => (
              <div
                key={index}
                className="flex items-center justify-between bg-muted p-3 rounded-lg"
              >
                <span className="text-sm text-foreground truncate flex-1">
                  {file.name}
                </span>
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  onClick={() => removeFile(index)}
                  disabled={isSubmitting}
                >
                  <X className="w-4 h-4" />
                </Button>
              </div>
            ))}
          </div>
        )}
      </div>

      <Button type="submit" disabled={isSubmitting} className="w-auto">
        {isSubmitting ? (
          <>
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            Submitting Ticket...
          </>
        ) : (
          "Submit Support Ticket"
        )}
      </Button>

      <p className="text-xs text-muted-foreground text-center">
        * Required fields. A ticket number will be generated for tracking purposes.
      </p>
    </form>
  );
};
